last_build_profile = "gtkada=RELEASE,libgtk3=RELEASE,libsdl2=RELEASE,libsdl2_image=RELEASE,libsdl2_mixer=RELEASE,libsdl2_ttf=RELEASE,make=RELEASE,pkg_config=RELEASE,sdlada=RELEASE,subterrania=DEVELOPMENT"

